version: "3.1"
services:
  db:
    image: mysql:5.7
    container_name: job-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'jobmarket'
      MYSQL_USER: 'ff'
      MYSQL_PASSWORD: ${mysql_ff_jobmarket}
      MYSQL_ROOT_PASSWORD: ${mysql_root_jobmarket}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./00_mysql_volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: job-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  mongodb:
    image : mongo:6.0-focal
    container_name: job-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'ff'
      MONGO_INITDB_ROOT_PASSWORD: ${mysql_ff_jobmarket}
    volumes :
      - ./01_mongodb_volume:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: job-mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ff
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${mysql_ff_jobmarket}
      - ME_CONFIG_MONGODB_URL=mongodb://ff:${mysql_ff_jobmarket}@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=${mexpress_password}
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
  dash:
    image: dash:latest
    container_name: job-dash
    volumes:
      - ./dash:/home/ubuntu
    environment:
      mysql_ff_jobmarket: ${mysql_ff_jobmarket}
    entrypoint: >
      /bin/sh -c 'python3 /home/ubuntu/my_dash.py'
    restart: always
    ports:
      - "5001:5000"
  fastapi:
    image: fastapi:latest
    container_name: job-fastapi
    volumes:
      - ./fastapi:/home/ubuntu
    environment:
      mysql_ff_jobmarket: ${mysql_ff_jobmarket}
    restart: always
    ports:
      - "8888:8888"